/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenDialog: typeof import('./src/components/Dialogs/TokenDialog.vue')['default']
    UserAvatar: typeof import('./src/components/User/UserAvatar.vue')['default']
    UserList: typeof import('./src/components/User/UserList.vue')['default']
  }
}
